/**
 * Type declarations for the WASM geodesic LUT module.
 * Generated by wasm-pack from rust/geodesic-lut.
 * This tells TypeScript how to handle the dynamic import.
 */

declare module "/wasm/geodesic_lut.js" {
  /** Computes a 512×512 RGBA Float32 lookup table of Schwarzschild geodesics. */
  export function compute_geodesic_lut(): Float32Array;

  /** Returns the LUT dimensions (512). */
  export function lut_size(): number;

  /** Initialize the WASM module. Must be called before other exports. */
  export default function init(): Promise<void>;
}
